### ISSUE TITLE
Add Data Sources to Axual TerraForm Provider

### ISSUE THREAD

**Issue by caspereijkens** [Axual/terraform-provider-axual#3]
We would like to see support for TF data sources. [Data sources allow Terraform to use information defined outside of Terraform, defined by another separate Terraform configuration, or modified by functions.](https://developer.hashicorp.com/terraform/language/data-sources)

This is important to us, because it helps managing each Axual namespace with a separate TerraForm configuration (statefile).

**Comment by kasparAxual** [comment]
Hey @caspereijkens. We now support TF data sources since v2.1.0.

Kindly find the example for data sources here(example is with a topic): https://registry.terraform.io/providers/Axual/axual/latest/docs/data-sources/topic

Here is our design that features managing separate Terraform configuraton statefiles in different repositories:
![image](https://github.com/Axual/terraform-provider-axual/assets/115068027/50052378-1dee-499a-a488-6ac2f0e23bc9)

**Comment by caspereijkens** [comment]
Very happy with this, thanks.
